Use customer_behavior;
Select * from Customer limit 20; 

-- Q1. What is the total revenue generated by male vs. female customers?
Select gender, Sum(purchase_amount) as "Total Revenue"
From Customer
Group By gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
Select customer_id, purchase_amount
From Customer
Where discount_applied = 'Yes' and purchase_amount >= (Select Avg(purchase_amount) From Customer);

-- Q3. Which are the top 5 products with the highest average review rating?
Select item_purchased as products, Round(Avg(review_rating),2) as "Average Product Rating"
From Customer 
Group by products
Order by Avg(review_rating) Desc
Limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
Select shipping_type, Round(Avg(purchase_amount),2) as 'Average Amount'
From Customer 
Where shipping_type in('Standard', 'Express')
Group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
Select subscription_status, 
Count(customer_id) as total_customers,
Round(Avg(purchase_amount),2) as avg_spend,
Round(Sum(purchase_amount),2) as total_revenue
From Customer 
Group by subscription_status
Order by total_revenue, avg_spend Desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
Select item_purchased, 
Round(100 * Sum(Case When discount_applied = 'Yes' Then 1 Else 0 End)/Count(*), 2) as discount_rate
From Customer 
Group by item_purchased
Order by discount_rate Desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
With customer_type as (
	Select customer_id, previous_purchases, 
    Case 
    When previous_purchases = 1 Then 'New'
    When previous_purchases Between 2 And 10 Then 'Returning'
    Else 'Loyal'
    End As customer_segment
    From Customer
)
Select customer_segment, count(*) as 'Number of Customers'
From customer_type
Group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
With item_counts as (
     Select category, item_purchased,
     Count(customer_id) as total_orders,
     ROW_NUMBER() Over(partition by category order by count(customer_id) Desc) as item_rank
     From customer
     Group by category, item_purchased
)
Select item_rank, category, item_purchased, total_orders
From item_counts
Where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select subscription_status,
Count(customer_id) as repeat_buyers
From customer  
Where previous_purchases > 5
Group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
Select age_group,
Sum(purchase_amount) as total_revenue
From Customer
Group by age_group 
Order by total_revenue Desc;